### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by MeggyCal** [IntQuant/OmniCamera#2]
Hi, thank you for all your hard work on this library. However, `omni-camera` doesn't compile on Python 3.12 due to outdated requirement on `pyo3`, which added support for Python 3.12 in version 0.20. Could you please take a look at it?

The error is:

```
[   57s]   Running `maturin pep517 build-wheel -i /usr/bin/python3.12 --compatibility off`
[   57s]   📦 Including license file "/home/abuild/rpmbuild/BUILD/omni_camera-0.6.0/LICENSE"
[   57s]   🍹 Building a mixed python/rust project
[   57s]   🔗 Found pyo3 bindings
[   57s]   🐍 Found CPython 3.12 at /usr/bin/python3.12
[   58s]      Compiling pyo3-build-config v0.15.2
[   58s]      Compiling pyo3-macros-backend v0.15.2
[   58s]      Compiling pyo3 v0.15.2
[   59s]      Compiling pyo3-macros v0.15.2
[   60s]   error[E0425]: cannot find function, tuple struct or tuple variant `PyUnicode_READY` in module `ffi`
[   60s]      --> /home/abuild/rpmbuild/BUILD/omni_camera-0.6.0/vendor/pyo3/src/types/string.rs:232:30
[   60s]       |
[   60s]   232 |             let ready = ffi::PyUnicode_READY(ptr);
[   60s]       |                              ^^^^^^^^^^^^^^^ help: a function with a similar name exists: `PyUnicode_IS_READY`
[   60s]       |
[   60s]      ::: /home/abuild/rpmbuild/BUILD/omni_camera-0.6.0/vendor/pyo3/src/ffi/cpython/unicodeobject.rs:224:1
[   60s]       |
[   60s]   224 | pub unsafe fn PyUnicode_IS_READY(op: *mut PyObject) -> c_uint {
[   60s]       | ------------------------------------------------------------- similarly named function `PyUnicode_IS_READY` defined here
[   60s] 
[   61s]   For more information about this error, try `rustc --explain E0425`.
[   61s]   error: could not compile `pyo3` (lib) due to 1 previous error
[   61s]   💥 maturin failed
[   61s]     Caused by: Failed to build a native library through cargo
[   61s]     Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/usr/bin/python3.12" PYTHON_SYS_EXECUTABLE="/usr/bin/python3.12" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/abuild/rpmbuild/BUILD/omni_camera-0.6.0/Cargo.toml" "--release" "--lib"`
```

**Comment by IntQuant** [comment]
Hi, thanks for submitting an issue. Library should build on python3.12 now.

**Comment by MeggyCal** [comment]
Thanks, it builds now :)
