### ISSUE TITLE
Fail to build with python 3.12.3+

### ISSUE THREAD

**Issue by mimi1vx** [IntQuant/OmniCamera#3]
Too old Py3O causes fail during build

```
[   66s]   🐍 Found CPython 3.12 at /usr/bin/python3.12
[   66s]      Compiling pyo3-build-config v0.15.2
[   66s]      Compiling pyo3-macros-backend v0.15.2
[   66s]      Compiling pyo3 v0.15.2
[   68s]      Compiling pyo3-macros v0.15.2
[   68s]   error[E0425]: cannot find function, tuple struct or tuple variant `PyUnicode_READY` in module `ffi`
[   68s]      --> /home/abuild/rpmbuild/BUILD/omni_camera-0.6.0/vendor/pyo3/src/types/string.rs:232:30
[   68s]       |
[   68s]   232 |             let ready = ffi::PyUnicode_READY(ptr);
[   68s]       |                              ^^^^^^^^^^^^^^^ help: a function with a similar name exists: `PyUnicode_IS_READY`
[   68s]       |
[   68s]      ::: /home/abuild/rpmbuild/BUILD/omni_camera-0.6.0/vendor/pyo3/src/ffi/cpython/unicodeobject.rs:224:1
[   68s]       |[
[   68s]   224 | pub unsafe fn PyUnicode_IS_READY(op: *mut PyObject) -> c_uint {
[   68s]       | ------------------------------------------------------------- similarly named function `PyUnicode_IS_READY` defined here
[   68s] 
[   70s]   For more information about this error, try `rustc --explain E0425`.
[   70s]   error: could not compile `pyo3` (lib) due to 1 previous error
[   70s]   💥 maturin failed
[   70s]     Caused by: Failed to build a native library through cargo
[   70s]     Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/usr/bin/python3.12" PYTHON_SYS_EXECUTABLE="/usr/bin/python3.12" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/abuild/rpmbuild/BUILD/omni_camera-0.6.0/Cargo.toml" "--release" "--lib"`
[   70s]   Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/bin/python3.12', '--compatibility', 'off'] returned non-zero exit status 1
[   70s]   error: subprocess-exited-with-error
[   70s]   
[   70s]   × Building wheel for omni_camera (pyproject.toml) did not run successfully.
[   70s]   │ exit code: 1
[   70s]   ╰─> See above for output.
```

**Comment by IntQuant** [comment]
Hi, thanks for submitting an issue. Library should build on python3.12 now.
